language: ruby
rvm:
- 2.1.2
addons:
  postgresql: "9.3"
deploy:
  provider: heroku
  api_key:
    secure: DkubZLUCpf6T8bEz0AGtk9HmTaDFPZvllUrdzr3C130YoGV8D0nKQdO1Vi0hBUvTPtzVckPb1YPMNvqzVmRHCMa1s7Bo8HsJZd3K/Jct4P9aulH6/HQkwLIdyo3R62/c2MCEag3CTWK1oOCS1V6YaoNGeb30mlFzAoXRzPBFKUg=
  app: beast-mode
  run:
    - "bundle exec rake db:migrate"
before_script:
  - psql -c 'create database beast_mode_test;' -U postgres